spring:
  config:
    import: "optional:consul:localhost:8500/redis/config;my-team"

  ##https://docs.spring.io/spring-cloud-consul/docs/current/reference/html/appendix.html
  cloud:
    consul:
      config:
        enabled: true
        fail-fast: true
        watch:
          wait-time: 5
          delay: 100
          enabled: true


common:
  greeting: "HellOoo, %s!"
  delay: 1


logging:
  level:
    ROOT: INFO
    org.springframework.cloud.config: DEBUG
    org.springframework.cloud.consul.config: DEBUG
